name: CrossChat
version: 1.3.1
main: io.github.dohwan.chat.CrossChatPlugin
api-version: "26.1.2"
author: MeatRoast
depend: [SQLDB]
commands:
  채팅모드:
    description: 채팅 모드를 변경합니다.
    usage: /채팅모드 <전체|서버|지역>
  닉네임:
    description: 닉네임을 변경합니다.
    usage: /닉네임 변경 <변경할닉네임>
  채팅아이템:
    description: 채팅 관련 아이템을 지급합니다.
    usage: /채팅아이템 <색채팅|닉변|색닉변> [플레이어]
